// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: distribution.sql

package db

import (
	"context"
	"database/sql"
)

const createDistributionHistory = `-- name: CreateDistributionHistory :one
INSERT INTO distribution_history (project_id, user_id, kind, provider, environment, snapshot_json)
SELECT p.id, p.user_id, ?1, ?2, ?3, ?4
FROM projects p WHERE p.id = ?5 AND p.user_id = ?6
RETURNING id, project_id, user_id, kind, provider, environment, status, provider_status, remote_id, message, snapshot_json, created_at, updated_at
`

type CreateDistributionHistoryParams struct {
	Kind         string `json:"kind"`
	Provider     string `json:"provider"`
	Environment  string `json:"environment"`
	SnapshotJson string `json:"snapshot_json"`
	ProjectID    int64  `json:"project_id"`
	UserID       int64  `json:"user_id"`
}

func (q *Queries) CreateDistributionHistory(ctx context.Context, arg CreateDistributionHistoryParams) (DistributionHistory, error) {
	row := q.db.QueryRowContext(ctx, createDistributionHistory,
		arg.Kind,
		arg.Provider,
		arg.Environment,
		arg.SnapshotJson,
		arg.ProjectID,
		arg.UserID,
	)
	var i DistributionHistory
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Kind,
		&i.Provider,
		&i.Environment,
		&i.Status,
		&i.ProviderStatus,
		&i.RemoteID,
		&i.Message,
		&i.SnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDistributionHistory = `-- name: GetDistributionHistory :one
SELECT h.id, h.project_id, h.user_id, h.kind, h.provider, h.environment, h.status, h.provider_status, h.remote_id, h.message, h.snapshot_json, h.created_at, h.updated_at FROM distribution_history h JOIN projects p ON p.id = h.project_id
WHERE h.id = ? AND h.project_id = ? AND h.user_id = ? AND p.user_id = h.user_id
`

type GetDistributionHistoryParams struct {
	ID        int64 `json:"id"`
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) GetDistributionHistory(ctx context.Context, arg GetDistributionHistoryParams) (DistributionHistory, error) {
	row := q.db.QueryRowContext(ctx, getDistributionHistory, arg.ID, arg.ProjectID, arg.UserID)
	var i DistributionHistory
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Kind,
		&i.Provider,
		&i.Environment,
		&i.Status,
		&i.ProviderStatus,
		&i.RemoteID,
		&i.Message,
		&i.SnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDistributionPreparation = `-- name: GetDistributionPreparation :one
SELECT dp.project_id, dp.preparation_json, dp.updated_at FROM distribution_preparations dp
JOIN projects p ON p.id = dp.project_id
WHERE dp.project_id = ? AND p.user_id = ?
`

type GetDistributionPreparationParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) GetDistributionPreparation(ctx context.Context, arg GetDistributionPreparationParams) (DistributionPreparation, error) {
	row := q.db.QueryRowContext(ctx, getDistributionPreparation, arg.ProjectID, arg.UserID)
	var i DistributionPreparation
	err := row.Scan(&i.ProjectID, &i.PreparationJson, &i.UpdatedAt)
	return i, err
}

const getDistributionProfile = `-- name: GetDistributionProfile :one
SELECT user_id, profile_json, updated_at FROM distribution_artist_profiles WHERE user_id = ?
`

func (q *Queries) GetDistributionProfile(ctx context.Context, userID int64) (DistributionArtistProfile, error) {
	row := q.db.QueryRowContext(ctx, getDistributionProfile, userID)
	var i DistributionArtistProfile
	err := row.Scan(&i.UserID, &i.ProfileJson, &i.UpdatedAt)
	return i, err
}

const listDistributionHistory = `-- name: ListDistributionHistory :many
SELECT h.id, h.project_id, h.user_id, h.kind, h.provider, h.environment, h.status, h.provider_status, h.remote_id, h.message, h.snapshot_json, h.created_at, h.updated_at FROM distribution_history h JOIN projects p ON p.id = h.project_id
WHERE h.project_id = ? AND h.user_id = ? AND p.user_id = h.user_id
ORDER BY h.id DESC
`

type ListDistributionHistoryParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) ListDistributionHistory(ctx context.Context, arg ListDistributionHistoryParams) ([]DistributionHistory, error) {
	rows, err := q.db.QueryContext(ctx, listDistributionHistory, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DistributionHistory{}
	for rows.Next() {
		var i DistributionHistory
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Kind,
			&i.Provider,
			&i.Environment,
			&i.Status,
			&i.ProviderStatus,
			&i.RemoteID,
			&i.Message,
			&i.SnapshotJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistributionTracks = `-- name: ListDistributionTracks :many
SELECT t.id, t.title, t.artist, t.active_version_id, tv.duration_seconds,
       tf.id AS file_id, tf.file_path, tf.file_size, tf.format, tf.original_filename
FROM tracks t
JOIN projects p ON p.id = t.project_id
LEFT JOIN track_versions tv ON tv.id = t.active_version_id AND tv.track_id = t.id
LEFT JOIN track_files tf ON tf.version_id = tv.id AND tf.quality = 'source' AND tf.transcoding_status = 'completed'
WHERE p.id = ? AND p.user_id = ?
ORDER BY t.track_order, t.id
`

type ListDistributionTracksParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

type ListDistributionTracksRow struct {
	ID               int64           `json:"id"`
	Title            string          `json:"title"`
	Artist           sql.NullString  `json:"artist"`
	ActiveVersionID  sql.NullInt64   `json:"active_version_id"`
	DurationSeconds  sql.NullFloat64 `json:"duration_seconds"`
	FileID           sql.NullInt64   `json:"file_id"`
	FilePath         sql.NullString  `json:"file_path"`
	FileSize         sql.NullInt64   `json:"file_size"`
	Format           sql.NullString  `json:"format"`
	OriginalFilename sql.NullString  `json:"original_filename"`
}

func (q *Queries) ListDistributionTracks(ctx context.Context, arg ListDistributionTracksParams) ([]ListDistributionTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, listDistributionTracks, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistributionTracksRow{}
	for rows.Next() {
		var i ListDistributionTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.ActiveVersionID,
			&i.DurationSeconds,
			&i.FileID,
			&i.FilePath,
			&i.FileSize,
			&i.Format,
			&i.OriginalFilename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveDistributionPreparation = `-- name: SaveDistributionPreparation :execrows
INSERT INTO distribution_preparations (project_id, preparation_json)
SELECT id, ?1 FROM projects WHERE id = ?2 AND user_id = ?3
ON CONFLICT(project_id) DO UPDATE SET preparation_json = excluded.preparation_json, updated_at = CURRENT_TIMESTAMP
`

type SaveDistributionPreparationParams struct {
	PreparationJson string `json:"preparation_json"`
	ProjectID       int64  `json:"project_id"`
	UserID          int64  `json:"user_id"`
}

func (q *Queries) SaveDistributionPreparation(ctx context.Context, arg SaveDistributionPreparationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveDistributionPreparation, arg.PreparationJson, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveDistributionProfile = `-- name: SaveDistributionProfile :exec
INSERT INTO distribution_artist_profiles (user_id, profile_json) VALUES (?, ?)
ON CONFLICT(user_id) DO UPDATE SET profile_json = excluded.profile_json, updated_at = CURRENT_TIMESTAMP
`

type SaveDistributionProfileParams struct {
	UserID      int64  `json:"user_id"`
	ProfileJson string `json:"profile_json"`
}

func (q *Queries) SaveDistributionProfile(ctx context.Context, arg SaveDistributionProfileParams) error {
	_, err := q.db.ExecContext(ctx, saveDistributionProfile, arg.UserID, arg.ProfileJson)
	return err
}

const updateDistributionHistory = `-- name: UpdateDistributionHistory :one
UPDATE distribution_history
SET status = COALESCE(?1, status),
    remote_id = COALESCE(?2, remote_id),
    provider_status = COALESCE(?3, provider_status),
    message = COALESCE(?4, message), updated_at = CURRENT_TIMESTAMP
WHERE distribution_history.id = ?5
  AND distribution_history.project_id = ?6
  AND distribution_history.user_id = ?7
  AND status = 'pending'
  AND EXISTS (SELECT 1 FROM projects p WHERE p.id = distribution_history.project_id AND p.user_id = distribution_history.user_id)
RETURNING id, project_id, user_id, kind, provider, environment, status, provider_status, remote_id, message, snapshot_json, created_at, updated_at
`

type UpdateDistributionHistoryParams struct {
	Status         sql.NullString `json:"status"`
	RemoteID       sql.NullString `json:"remote_id"`
	ProviderStatus sql.NullString `json:"provider_status"`
	Message        sql.NullString `json:"message"`
	ID             int64          `json:"id"`
	ProjectID      int64          `json:"project_id"`
	UserID         int64          `json:"user_id"`
}

func (q *Queries) UpdateDistributionHistory(ctx context.Context, arg UpdateDistributionHistoryParams) (DistributionHistory, error) {
	row := q.db.QueryRowContext(ctx, updateDistributionHistory,
		arg.Status,
		arg.RemoteID,
		arg.ProviderStatus,
		arg.Message,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
	)
	var i DistributionHistory
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Kind,
		&i.Provider,
		&i.Environment,
		&i.Status,
		&i.ProviderStatus,
		&i.RemoteID,
		&i.Message,
		&i.SnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDistributionRemoteStatus = `-- name: UpdateDistributionRemoteStatus :one
UPDATE distribution_history
SET provider_status = ?,
    message = CASE WHEN ?5 = '' THEN message ELSE ?5 END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND project_id = ? AND user_id = ? AND provider != '' AND remote_id != ''
RETURNING id, project_id, user_id, kind, provider, environment, status, provider_status, remote_id, message, snapshot_json, created_at, updated_at
`

type UpdateDistributionRemoteStatusParams struct {
	ProviderStatus string      `json:"provider_status"`
	Message        interface{} `json:"message"`
	ID             int64       `json:"id"`
	ProjectID      int64       `json:"project_id"`
	UserID         int64       `json:"user_id"`
}

func (q *Queries) UpdateDistributionRemoteStatus(ctx context.Context, arg UpdateDistributionRemoteStatusParams) (DistributionHistory, error) {
	row := q.db.QueryRowContext(ctx, updateDistributionRemoteStatus,
		arg.ProviderStatus,
		arg.Message,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
	)
	var i DistributionHistory
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Kind,
		&i.Provider,
		&i.Environment,
		&i.Status,
		&i.ProviderStatus,
		&i.RemoteID,
		&i.Message,
		&i.SnapshotJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
