// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preferences.sql

package db

import (
	"context"
	"database/sql"
)

const createUserPreferences = `-- name: CreateUserPreferences :exec
INSERT INTO user_preferences (user_id, default_quality)
VALUES (?, ?)
`

type CreateUserPreferencesParams struct {
	UserID         int64  `json:"user_id"`
	DefaultQuality string `json:"default_quality"`
}

func (q *Queries) CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, createUserPreferences, arg.UserID, arg.DefaultQuality)
	return err
}

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, default_quality, created_at, updated_at, disc_colors, color_spread, gradient_spread, color_shift_rotation, accent_color, theme, system_dark_theme FROM user_preferences
WHERE user_id = ?
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID int64) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.DefaultQuality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiscColors,
		&i.ColorSpread,
		&i.GradientSpread,
		&i.ColorShiftRotation,
		&i.AccentColor,
		&i.Theme,
		&i.SystemDarkTheme,
	)
	return i, err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE user_preferences
SET default_quality = COALESCE(?1, default_quality),
    disc_colors = COALESCE(?2, disc_colors),
    color_spread = COALESCE(?3, color_spread),
    gradient_spread = COALESCE(?4, gradient_spread),
    color_shift_rotation = COALESCE(?5, color_shift_rotation),
    accent_color = COALESCE(?6, accent_color),
    theme = COALESCE(?7, theme),
    system_dark_theme = COALESCE(?8, system_dark_theme),
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = ?9
RETURNING user_id, default_quality, created_at, updated_at, disc_colors, color_spread, gradient_spread, color_shift_rotation, accent_color, theme, system_dark_theme
`

type UpdateUserPreferencesParams struct {
	DefaultQuality     sql.NullString `json:"default_quality"`
	DiscColors         sql.NullString `json:"disc_colors"`
	ColorSpread        sql.NullInt64  `json:"color_spread"`
	GradientSpread     sql.NullInt64  `json:"gradient_spread"`
	ColorShiftRotation sql.NullInt64  `json:"color_shift_rotation"`
	AccentColor        sql.NullString `json:"accent_color"`
	Theme              sql.NullString `json:"theme"`
	SystemDarkTheme    sql.NullString `json:"system_dark_theme"`
	UserID             int64          `json:"user_id"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, updateUserPreferences,
		arg.DefaultQuality,
		arg.DiscColors,
		arg.ColorSpread,
		arg.GradientSpread,
		arg.ColorShiftRotation,
		arg.AccentColor,
		arg.Theme,
		arg.SystemDarkTheme,
		arg.UserID,
	)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.DefaultQuality,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiscColors,
		&i.ColorSpread,
		&i.GradientSpread,
		&i.ColorShiftRotation,
		&i.AccentColor,
		&i.Theme,
		&i.SystemDarkTheme,
	)
	return i, err
}
