// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_settings.sql

package db

import (
	"context"
)

const getProviderSetting = `-- name: GetProviderSetting :one
SELECT provider, encrypted_config, created_at, updated_at FROM provider_settings WHERE provider = ?
`

func (q *Queries) GetProviderSetting(ctx context.Context, provider string) (ProviderSetting, error) {
	row := q.db.QueryRowContext(ctx, getProviderSetting, provider)
	var i ProviderSetting
	err := row.Scan(
		&i.Provider,
		&i.EncryptedConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveProviderSetting = `-- name: SaveProviderSetting :exec
INSERT INTO provider_settings (provider, encrypted_config)
VALUES (?, ?)
ON CONFLICT(provider) DO UPDATE SET
    encrypted_config = excluded.encrypted_config,
    updated_at = CURRENT_TIMESTAMP
`

type SaveProviderSettingParams struct {
	Provider        string `json:"provider"`
	EncryptedConfig []byte `json:"encrypted_config"`
}

func (q *Queries) SaveProviderSetting(ctx context.Context, arg SaveProviderSettingParams) error {
	_, err := q.db.ExecContext(ctx, saveProviderSetting, arg.Provider, arg.EncryptedConfig)
	return err
}
