// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_connections.sql

package db

import (
	"context"
)

const consumeProviderOAuthState = `-- name: ConsumeProviderOAuthState :one
DELETE FROM provider_oauth_states WHERE state_hash = ? AND expires_at > ? RETURNING state_hash, user_id, provider, environment, encrypted_verifier, expires_at
`

type ConsumeProviderOAuthStateParams struct {
	StateHash string `json:"state_hash"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) ConsumeProviderOAuthState(ctx context.Context, arg ConsumeProviderOAuthStateParams) (ProviderOauthState, error) {
	row := q.db.QueryRowContext(ctx, consumeProviderOAuthState, arg.StateHash, arg.ExpiresAt)
	var i ProviderOauthState
	err := row.Scan(
		&i.StateHash,
		&i.UserID,
		&i.Provider,
		&i.Environment,
		&i.EncryptedVerifier,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteProviderConnection = `-- name: DeleteProviderConnection :exec
DELETE FROM provider_connections WHERE user_id = ? AND provider = ? AND environment = ?
`

type DeleteProviderConnectionParams struct {
	UserID      int64  `json:"user_id"`
	Provider    string `json:"provider"`
	Environment string `json:"environment"`
}

func (q *Queries) DeleteProviderConnection(ctx context.Context, arg DeleteProviderConnectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteProviderConnection, arg.UserID, arg.Provider, arg.Environment)
	return err
}

const deleteProviderOAuthStates = `-- name: DeleteProviderOAuthStates :exec
DELETE FROM provider_oauth_states WHERE user_id = ? AND provider = ? AND environment = ?
`

type DeleteProviderOAuthStatesParams struct {
	UserID      int64  `json:"user_id"`
	Provider    string `json:"provider"`
	Environment string `json:"environment"`
}

func (q *Queries) DeleteProviderOAuthStates(ctx context.Context, arg DeleteProviderOAuthStatesParams) error {
	_, err := q.db.ExecContext(ctx, deleteProviderOAuthStates, arg.UserID, arg.Provider, arg.Environment)
	return err
}

const expireProviderOAuthStates = `-- name: ExpireProviderOAuthStates :exec
DELETE FROM provider_oauth_states WHERE expires_at <= ?
`

func (q *Queries) ExpireProviderOAuthStates(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, expireProviderOAuthStates, expiresAt)
	return err
}

const getProviderConnection = `-- name: GetProviderConnection :one
SELECT user_id, provider, environment, encrypted_token, updated_at FROM provider_connections WHERE user_id = ? AND provider = ? AND environment = ?
`

type GetProviderConnectionParams struct {
	UserID      int64  `json:"user_id"`
	Provider    string `json:"provider"`
	Environment string `json:"environment"`
}

func (q *Queries) GetProviderConnection(ctx context.Context, arg GetProviderConnectionParams) (ProviderConnection, error) {
	row := q.db.QueryRowContext(ctx, getProviderConnection, arg.UserID, arg.Provider, arg.Environment)
	var i ProviderConnection
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.Environment,
		&i.EncryptedToken,
		&i.UpdatedAt,
	)
	return i, err
}

const saveProviderConnection = `-- name: SaveProviderConnection :exec
INSERT INTO provider_connections (user_id, provider, environment, encrypted_token)
VALUES (?, ?, ?, ?)
ON CONFLICT(user_id, provider, environment) DO UPDATE SET encrypted_token = excluded.encrypted_token, updated_at = CURRENT_TIMESTAMP
`

type SaveProviderConnectionParams struct {
	UserID         int64  `json:"user_id"`
	Provider       string `json:"provider"`
	Environment    string `json:"environment"`
	EncryptedToken []byte `json:"encrypted_token"`
}

func (q *Queries) SaveProviderConnection(ctx context.Context, arg SaveProviderConnectionParams) error {
	_, err := q.db.ExecContext(ctx, saveProviderConnection,
		arg.UserID,
		arg.Provider,
		arg.Environment,
		arg.EncryptedToken,
	)
	return err
}

const saveProviderOAuthState = `-- name: SaveProviderOAuthState :exec
INSERT INTO provider_oauth_states (state_hash, user_id, provider, environment, encrypted_verifier, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id, provider, environment) DO UPDATE SET state_hash = excluded.state_hash, encrypted_verifier = excluded.encrypted_verifier, expires_at = excluded.expires_at
`

type SaveProviderOAuthStateParams struct {
	StateHash         string `json:"state_hash"`
	UserID            int64  `json:"user_id"`
	Provider          string `json:"provider"`
	Environment       string `json:"environment"`
	EncryptedVerifier []byte `json:"encrypted_verifier"`
	ExpiresAt         int64  `json:"expires_at"`
}

func (q *Queries) SaveProviderOAuthState(ctx context.Context, arg SaveProviderOAuthStateParams) error {
	_, err := q.db.ExecContext(ctx, saveProviderOAuthState,
		arg.StateHash,
		arg.UserID,
		arg.Provider,
		arg.Environment,
		arg.EncryptedVerifier,
		arg.ExpiresAt,
	)
	return err
}
