// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: waveform_comments.sql

package db

import (
	"context"
	"database/sql"
)

const createWaveformComment = `-- name: CreateWaveformComment :one
INSERT INTO waveform_comments (
    version_id, user_id, author_name, comment_text, timestamp_seconds
)
VALUES (?, ?, ?, ?, ?)
RETURNING id, version_id, user_id, author_name, comment_text, timestamp_seconds, created_at
`

type CreateWaveformCommentParams struct {
	VersionID        int64         `json:"version_id"`
	UserID           sql.NullInt64 `json:"user_id"`
	AuthorName       string        `json:"author_name"`
	CommentText      string        `json:"comment_text"`
	TimestampSeconds float64       `json:"timestamp_seconds"`
}

func (q *Queries) CreateWaveformComment(ctx context.Context, arg CreateWaveformCommentParams) (WaveformComment, error) {
	row := q.db.QueryRowContext(ctx, createWaveformComment,
		arg.VersionID,
		arg.UserID,
		arg.AuthorName,
		arg.CommentText,
		arg.TimestampSeconds,
	)
	var i WaveformComment
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.UserID,
		&i.AuthorName,
		&i.CommentText,
		&i.TimestampSeconds,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWaveformComment = `-- name: DeleteWaveformComment :execrows
DELETE FROM waveform_comments
WHERE id = ? AND user_id = ?
`

type DeleteWaveformCommentParams struct {
	ID     int64         `json:"id"`
	UserID sql.NullInt64 `json:"user_id"`
}

func (q *Queries) DeleteWaveformComment(ctx context.Context, arg DeleteWaveformCommentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWaveformComment, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listWaveformCommentsByVersion = `-- name: ListWaveformCommentsByVersion :many
SELECT id, version_id, user_id, author_name, comment_text, timestamp_seconds, created_at FROM waveform_comments
WHERE version_id = ?
ORDER BY timestamp_seconds ASC, created_at ASC
`

func (q *Queries) ListWaveformCommentsByVersion(ctx context.Context, versionID int64) ([]WaveformComment, error) {
	rows, err := q.db.QueryContext(ctx, listWaveformCommentsByVersion, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaveformComment{}
	for rows.Next() {
		var i WaveformComment
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.UserID,
			&i.AuthorName,
			&i.CommentText,
			&i.TimestampSeconds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWaveformComment = `-- name: UpdateWaveformComment :one
UPDATE waveform_comments
SET comment_text = ?
WHERE id = ? AND user_id = ?
RETURNING id, version_id, user_id, author_name, comment_text, timestamp_seconds, created_at
`

type UpdateWaveformCommentParams struct {
	CommentText string        `json:"comment_text"`
	ID          int64         `json:"id"`
	UserID      sql.NullInt64 `json:"user_id"`
}

func (q *Queries) UpdateWaveformComment(ctx context.Context, arg UpdateWaveformCommentParams) (WaveformComment, error) {
	row := q.db.QueryRowContext(ctx, updateWaveformComment, arg.CommentText, arg.ID, arg.UserID)
	var i WaveformComment
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.UserID,
		&i.AuthorName,
		&i.CommentText,
		&i.TimestampSeconds,
		&i.CreatedAt,
	)
	return i, err
}
