CREATE TABLE provider_settings (
    provider TEXT PRIMARY KEY,
    encrypted_config BLOB NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
